URLopener was removed in Python 3.14 and hplip tracebacks without it
URLopener was removed in Python 3.14 in Fedora 43, which causes several hplip scripts to traceback.

For now I've applied the attached patch to remove URLopener, since hplip modules look like they don't use the methods from the class, but rather the method implemented in class LocalOpener, which inherits from URLOpener - major scripts like hp-plugin, hp-setup and hp-toolbox look to be working with the fix.

It would be great if URLopener was removed from hplip project and replaced if required - Fedora will try the attached patch for now to make hplip working to some extent in Fedora 43.

Traceback example:

/usr/share/hplip/prnt/cups.py:699: SyntaxWarning: 'return' in a 'finally' block
  return fax_ppd,expected_fax_ppd_name, nick
Traceback (most recent call last):
  File "/usr/bin/hp-plugin", line 41, in <module>
    from base import device, utils, tui, module, services
  File "/usr/share/hplip/base/device.py", line 2691, in <module>
    class LocalOpener(urllib_request.URLopener):
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib.request' has no attribute 'URLopener'